services:
  - type: web
    name: ScholarSync
    runtime: java
    rootDir: scholarsync
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17